[project]
name = "xlwings-testing"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "xlwings>=0.33.16",
    "polars (>=1.35.2,<2.0.0)",
    "openpyxl (>=3.1.5,<4.0.0)",
]
